# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: diversity
email: marie@dvsty.com
description: > # this means to ignore newlines until "baseurl:"
  Marie is a Freelance Visual- and Userexperience Designer working in Berlin, Munich and remote. Her specialty are touchable interfaces.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://beta.dvsty.com/" # the base hostname & protocol for your site
twitter_username: ma_rylou
github_username:  MarieSchweiz

# Build settings
markdown: kramdown

# exclude bash files
exclude: ['*.sh']